import type {NextPage} from 'next'

import {Storyblok} from '../lib/storyblok';
import DynamicComponent from "../components/storyblok/DynamicComponent"
import { PostList } from "../components/PostList"
import {Container} from "@chakra-ui/react";
import {Pagination} from "../components/Pagination";
import {PER_PAGE} from "../components/Pagination/Pagination";

const Home: NextPage = ({page, posts, currentPage, totalPosts}) => {
    return (
        <>
            {/*<Head>*/}
            {/*  <title>Create Next App</title>*/}
            {/*  <meta name="description" content="Generated by create next app" />*/}
            {/*  <link rel="icon" href="/favicon.ico" />*/}
            {/*</Head>*/}

            <main>
                <Container maxW="container.md">
                    {page && <DynamicComponent blok={page.content}/>}
                    <PostList items={posts.stories}/>
                    <Pagination currentPage={parseInt(currentPage, 10)} totalPosts={parseInt(totalPosts, 10)}/>
                </Container>
            </main>
        </>
    )
}

export default Home

export async function getStaticProps() {
    // home is the default slug for the homepage in Storyblok
    let slug = "home";

    // load the draft version
    let sbParams = {
        version: "draft", // or 'published'
    };

    let {data: page} = await Storyblok.get(`cdn/stories/${slug}`, sbParams);
    let {data: posts, total} = await Storyblok.get(`cdn/stories`, {
        starts_with: 'posts',
        per_page: PER_PAGE,
        page: 1
    });

    return {
        props: {
            page: page ? page.story : false,
            posts,
            key: page ? page.story.id : false,
            currentPage: 1,
            totalPosts: total,
        },
        revalidate: 3600, // revalidate every hour
    };
}
